# OP-TEE runs from pIMEM, with its TA RAM in RAMBLUR window 2.
$(call force,CFG_QCOM_RAMBLUR_PIMEM_V3,y)
CFG_QCOM_RAMBLUR_TA_WINDOW_ID ?= 2
CFG_TZDRAM_START ?= 0x1c300000

# Equal to RAMBLUR_PIMEM_VAULT_TA_SIZE: TA RAM is the RAMBLUR TA window
CFG_TA_RAM_VA_SIZE ?= 0x1a00000
